#pragma once

#include <Engine/Base.h>

SE_PRAGMA_WARNING_DISABLE_MSVC(4514)
SE_PRAGMA_WARNING_DISABLE_MSVC(4625)
SE_PRAGMA_WARNING_DISABLE_MSVC(4626)
SE_PRAGMA_WARNING_DISABLE_MSVC(4820)
SE_PRAGMA_WARNING_DISABLE_MSVC(5026)
SE_PRAGMA_WARNING_DISABLE_MSVC(5027)
SE_PRAGMA_WARNING_PUSH_LEVEL(0)
SE_PRAGMA_WARNING_DISABLE_MSVC(4668)

#include <fstream>
#include <chrono>

SE_PRAGMA_WARNING_POP


#include <Engine/Engine.h>